image: vincentcau/laravel-docker:7.3-fpm

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'cms_test'
        MYSQL_USER: 'cms_test'
        MYSQL_PASSWORD: 'secret'
        MYSQL_ROOT_PASSWORD: 'root'

  steps:
    - step: &build_dev
        name: Build dependencies
        script:
          - 'printf "{\"http-basic\": {\"nova.laravel.com\": {\"username\":\"$NOVA_USERNAME\", \"password\":\"$NOVA_PASSWORD\"}}}" > auth.json'
          - rm -f composer.lock
          - COMPOSER_MEMORY_LIMIT=-1 composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --no-suggest --optimize-autoloader
          - find vendor -name ".git" | xargs rm -rf
        artifacts:
          - vendor/**
          - auth.json
          - composer.lock

    - step: &tests
        name: Testing
        script:
          - ./vendor/bin/security-checker security:check
          - ./vendor/bin/phpcs --report=full
          - ./vendor/bin/psalm
          - ./vendor/bin/phpunit --no-coverage
        services:
          - mysql

pipelines:
  default:
    - step: *build_dev
    - step: *tests
