name: CMS CI
on: [push]
jobs:
  cms-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-20.04 ]
        php: [8.0, 8.1 ]
        laravel: [ 9.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 9.*
            testbench: ^6.6

    services:
      mysql:
        image: mariadb:10.5.8
        env:
          MYSQL_DATABASE: cms_test
          MYSQL_USER: cms_test
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:

      # Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - uses: actions/checkout@v2

      # Preparing environment
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-cms
          restore-keys: ${{ runner.os }}-composer-

      - name: Installing PHP dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      # Tests migrations
      - name: Testing migrations
        run: |
          ./vendor/bin/testbench migrate:fresh
          ./vendor/bin/testbench migrate:rollback
          ./vendor/bin/testbench migrate
        env:
          DB_PORT: 32574

      # Tests that just need composer dependencies
      - name: Running security checker
        run: ./bin/local-php-security-checker-linux

      - name: Running phpcs
        run: ./vendor/bin/phpcs --report=full

      - name: Running phpstan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon

      - name: Running phpunit
        run: ./vendor/bin/phpunit --no-coverage
        env:
          DB_PORT: 32574

      # On failure
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'CMS CI'
          SLACK_ICON_EMOJI: ':hinhin:'
          SLACK_TITLE: Dernier commit
          SLACK_FOOTER: "“Je ne comprends pas, pourtant ça marche en local.” — inconnu"
