name: CMS CI
on: [push]
jobs:
  cms-ci:
    runs-on: ubuntu-20.04
    name: "CI CMS"

    steps:

      # Setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2
          coverage: none

      - name: Setup NODE
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v2

      # Preparing environment
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-cms
          restore-keys: ${{ runner.os }}-composer-

      - name: Starting MySQL
        run: |
          sudo systemctl start mysql.service
          PRAGMA foreign_keys=1

      - name: Installing PHP dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer update --prefer-dist --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      # Tests migrations
      - name: Testing migrations
        run: |
          ./vendor/bin/testbench migrate:fresh
          ./vendor/bin/testbench migrate:rollback
          ./vendor/bin/testbench migrate

      # Tests that just need composer dependencies
      - name: Running security checker
        run: ./bin/local-php-security-checker-linux

      - name: Running phpcs
        run: ./vendor/bin/phpcs --report=full

      - name: Running phpstan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon

      - name: Running phpunit
        run: ./vendor/bin/phpunit --no-coverage
        env:
          DB_PORT: 32574

      # On failure
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FF5555'
          SLACK_USERNAME: 'CMS CI'
          SLACK_ICON_EMOJI: ':hinhin:'
          SLACK_TITLE: Dernier commit
          SLACK_FOOTER: "“Je ne comprends pas, pourtant ça marche en local.” — inconnu"
